I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 131, in script
    show hina frown small ar rightest
Exception: Image 'hina frown small' does not accept attributes 'ar rightest'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 131, in script
    show hina frown small ar rightest
  File "renpy/ast.py", line 1197, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy/ast.py", line 1167, in show_imspec
    atl=atl)
  File "renpy/exports.py", line 742, in show
    if not base.find_target() and renpy.config.missing_show:
  File "renpy/display/image.py", line 409, in find_target
    self.target = target._duplicate(a)
  File "renpy/display/core.py", line 390, in _duplicate
    args.extraneous()
  File "renpy/display/core.py", line 271, in extraneous
    " ".join(self.args),
Exception: Image 'hina frown small' does not accept attributes 'ar rightest'.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
School 1.0
Mon Mar 14 08:15:17 2022
